### PR TITLE
feat: add bitcoin icon

### PR DESCRIPTION
**Pull request by tunnckoCore**
because why not

### CODE REVIEW

**Comment by amio** [comment]
We can use external icon for this now

```
https://badgen.net/badge/bitcoin/bitcoin?icon=https://simpleicons.now.sh/bitcoin/fff&label
```

**Comment by tunnckoCore** [comment]
ooh cool, I always forgot about simpleicons.

**Comment by lukechilds** [comment]
@amio this can be closed now due to #22 :)

**Comment by amio** [comment]
Yep 👍

**Pull request closed without merging**
