### PR TITLE
feat: add Jira icon

### PR DESCRIPTION
**Pull request by stefanbuck**
Hey,

I'm using Badgen to generated badges used by https://pullrequestbadge.com/. One of the main use-cases of Pull Request Badge is adding a Jira badge to the pull request description. Therefore it would be super neat to have a Jira icon available. 

### Checklist

- [x] Optimize markup with [svgomg](https://jakearchibald.github.io/svgomg/)
- [x] Preview with [badgen-icons.now.sh](https://badgen-icons.now.sh/)

### Preview

image

### CODE REVIEW

**Comment by amio** [comment]
Seems Jira's icon has changed (again)? https://www.atlassian.com/software/jira

**Comment by stefanbuck** [comment]
Mhh if you scroll down on that page you see the logo I added. Also the android app is using this logo. The press kit page isn't helping either https://www.atlassian.com/de/company/news/press-kit

**Comment by amio** [comment]
@stefanbuck Is this jira mobile logo?

image

**Comment by stefanbuck** [comment]
Yes, but it's missing in their press kit page. To be honest I have no idea what the difference between all those JIRA products is. At work we use a self hosted JIRA instance and this is showing the logo I added which is inline with the mobile app logo. Maybe they are in the middle to roll out a new logo.

image

**Comment by stefanbuck** [comment]
From their product page it seems like JIRA Software is what we want https://www.atlassian.com/de/software/jira

**Comment by stefanbuck** [comment]
I updated the logo to match the press kit version

image

**Review by amio — APPROVED** [review]
Great, thanks! @stefanbuck

**Pull request merged**
