### PR TITLE
Add Ubiquiti Logo Icon

### PR DESCRIPTION
**Pull request by davidnewhall**
Hello,

I have a use for this icon. I tried several different ways to make `?icon=https://github.com/.../ubiquiti.svg` work, but it never shows up. It seems like there is a filter allowing icons to only come from specific sources. If that's the case, I wonder if you'd consider adding this for me? <3

u-icon-preview

Thank you!
-david

### CODE REVIEW

**Comment by amio** [comment]
@davidnewhall There's no filter limiting icon sources. Would you provide the full path for me to look into?

**Comment by davidnewhall** [comment]
Hello! Certainly.. I tried the following paths:
http://www.freelogovectors.net/svg03/ubiquiti_logo.svg << this is where I got the logo I've submitted in this contribution. I just changed all the colors to white using the tool you've linked from this repo's readme. Cool tricks. This URL probably doesn't work because the https variant redirects to http. Almost like someone made an oopsie because it has a valid SSL cert.

https://raw.githubusercontent.com/wiki/davidnewhall/unifi-poller/images/ubiquiti_logo.svg << I copied the logo into my repo's wiki space to see if I could use it from there. It just never seems to work, locally (using a markdown renderer), or once it's on github. Probably an issue with the content type header github returns for SVG files in a wiki path. Just not sure.

I sorta like the multi-colored SVG and would like to see how it looks on a badge, but I'm afraid it will need a background to look okay against all palettes. If you're able to show me how to use an icon from a github repo, that'd be pretty slick. Maybe some other "easy to host" tricks?

Thank you!

**Comment by amio** [comment]
The icon link needs a correct response header `content-type`, it could be `image/svg+xml` or `image/png` etc:

https://github.com/badgen/badgen.net/blob/4aee8467cfd45ad590dbf3d091bf6aaf2a25f822/libs/fetch-icon.ts#L5-L6

🤔 Maybe you could use https://svgur.com/ for svg hosting?

**Comment by davidnewhall** [comment]
Great info thank you! I can probably host this myself. Totally up to you if you wish to include it here.

**Comment by amio** [comment]
Nice! I'll close this PR then :D

**Comment by davidnewhall** [comment]
I made this too. Just wanted to share. Maybe there's a better place to share? ;)

https://github.com/golift/badgedata

**Comment by amio** [comment]
Guess we need a page or something to showcase fun/creative works like this 🦄

**Pull request closed without merging**
